### PR TITLE
update the space in header and buttons of shape and color

### PR DESCRIPTION
**Pull request by VirendrKumarYadav**
added space in buttons and header part of text

### CODE REVIEW

**Comment by jaitensahu** [comment]
pls, add screenshots of what changes you have made.

**Comment by VirendrKumarYadav** [comment]
before look like 
image
now
image

**Comment by VirendrKumarYadav** [comment]
Adjust some margin in header section.
image
image

**Comment by jaitensahu** [comment]
If you find our repository helpful, please consider starring it and giving us a follow. Your support is greatly appreciated!

**Pull request merged**
